import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/app/components/sidebar";
import ThemeProvider from "@/app/components/ThemeProvider";
import { ToastContainer } from "react-toastify";
import { Providers } from "@/app/providers";
import "./globals.css";
import AuthGuard from "@/app/validations/AuthGuard"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AuthGuard> */}
        <Providers>
          <ThemeProvider>

            <div className="drawer lg:drawer-open">

              <div className="drawer-content flex flex-col min-h-screen">

                <main className="flex-1">{children}</main>
              </div>
            </div>

            <ToastContainer
              position="bottom-right"
              autoClose={6000}
              pauseOnHover
              draggable
              toastClassName="custom-toast"
            />

          </ThemeProvider>
        </Providers>
        {/* </AuthGuard> */}
      </body>
    </html>
  );
}
